### ISSUE TITLE
Add information about the Expectations from Reviewers

### ISSUE THREAD

**Issue by jorainer** [kevinrue/bioc_package_guide#30]
Add also the information on the expectations from reviewers.

**Comment by kevinrue** [comment]
I'm happy to see some PRs, so that others can add themselves as authors in the DESCRIPTION file (shows up in the footer of the website)

**Comment by jorainer** [comment]
After some more thoughts I no longer think that it would be an information that needs to go to this bookdown. That info is relevant for the recruitment of new reviewers but not for the actual review or the package development.
