### ISSUE TITLE
Add authors

### ISSUE THREAD

**Issue by jorainer** [kevinrue/bioc_package_guide#33]
Listing all authors that contributed will be a key information in my opinion. The core BioC developer setting up the initial documentation should be for sure also listed there. I'm just not sure where and how to add that in a bookdown @kevinrue? Is it the same as with regular R packages?

**Comment by kevinrue** [comment]
At this point, authors are listed in the DESCRIPTION file, which is used to generate the list of authors in the footer of the compiled book.

![image](https://user-images.githubusercontent.com/5769108/120607955-9451a480-c448-11eb-8341-80d4df68524a.png)

We could also have a dedicated chapter, though I'd rather keep it DRY, and the footer is visible on every chapter.
That said, I'm not sure how big the footer will become when we reach dozens of authors.

This is how the ropensci footer looks like right now
https://devguide.ropensci.org/contributingguide.html

![image](https://user-images.githubusercontent.com/5769108/120608328-fca08600-c448-11eb-8b9a-227d25970b13.png)

**Comment by kevinrue** [comment]
I'll close this issue for now, since I explained how/where  to add authors and where they are listed in the deployed book.
